// <auto-generated />
using System;
using Helpdesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helpdesk.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615134933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Helpdesk.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Общие вопросы"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Техническая поддержка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Отчётность"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Доступы и права"
                        });
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.HistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.SlaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReactionHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SlaConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = "Low",
                            ReactionHours = 8,
                            ResolutionHours = 72
                        },
                        new
                        {
                            Id = 2,
                            Priority = "Medium",
                            ReactionHours = 4,
                            ResolutionHours = 24
                        },
                        new
                        {
                            Id = 3,
                            Priority = "High",
                            ReactionHours = 2,
                            ResolutionHours = 8
                        },
                        new
                        {
                            Id = 4,
                            Priority = "Critical",
                            ReactionHours = 0,
                            ResolutionHours = 4
                        });
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SlaBreached")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SlaPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SlaPausedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SlaPausedTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.TicketDependency", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId", "BlockedById");

                    b.HasIndex("BlockedById");

                    b.ToTable("TicketDependencies");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.TicketFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketFiles");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Comment", b =>
                {
                    b.HasOne("Helpdesk.Api.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpdesk.Api.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.HistoryEntry", b =>
                {
                    b.HasOne("Helpdesk.Api.Models.User", "Author")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpdesk.Api.Models.Ticket", "Ticket")
                        .WithMany("History")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Ticket", b =>
                {
                    b.HasOne("Helpdesk.Api.Models.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Helpdesk.Api.Models.User", "Author")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Helpdesk.Api.Models.Category", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.TicketDependency", b =>
                {
                    b.HasOne("Helpdesk.Api.Models.Ticket", "BlockedByTicket")
                        .WithMany("Blocking")
                        .HasForeignKey("BlockedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Helpdesk.Api.Models.Ticket", "Ticket")
                        .WithMany("BlockedBy")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlockedByTicket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.TicketFile", b =>
                {
                    b.HasOne("Helpdesk.Api.Models.Ticket", "Ticket")
                        .WithMany("Files")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Category", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.Ticket", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("Blocking");

                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("History");
                });

            modelBuilder.Entity("Helpdesk.Api.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTickets");

                    b.Navigation("HistoryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
